import {
  Box,
  Button,
  Checkbox,
  IconButton,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import Head from "next/head";
import FacebookRoundedIcon from "@mui/icons-material/FacebookRounded";
import GoogleIcon from "@mui/icons-material/Google";
import Router from "next/router";

export default function LoginPage() {
  return (
    <div>
      <Head>
        <title>Change password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Stack direction="row">
          <Box flex={1} bgcolor="#fff" height="100vh" color="#000">
            <img
              src="/img/bg-login.png"
              width="100%"
              alt="img"
              className="img-fluid"
            />
          </Box>
          <Box
            flex={1}
            bgcolor="#fff"
            height="100vh"
            color="#000"
            padding={2}
            display="flex"
            alignItems="center"
          >
            <Stack alignItems="center" gap={2} maxWidth={600} flex={1}>
              <h1 className="d-flex gap-2 m-0">
                <Typography fontSize={30} sx={{ color: "#FFB744" }}>
                  DAISYLIGHT
                </Typography>
                -<Typography fontSize={30}>Quên mật khẩu</Typography>
              </h1>
              <p>Vui lòng nhập email để lấy lại mật khẩu của bạn.</p>
              <TextField
                id="outlined-basic"
                label="Email"
                variant="outlined"
                sx={{
                  marginTop: 2,
                  width: "100%",
                }}
              />
              <Button
                variant="contained"
                color="primary"
                fullWidth
                sx={{
                  marginTop: 3,
                }}
                onClick={() => Router.push("/login")}
              >
                Lấy lại mật khẩu
              </Button>
            </Stack>
          </Box>
        </Stack>
      </Box>
    </div>
  );
}
