import { Box, Button, IconButton, Stack, TextField } from "@mui/material";
import Head from "next/head";
import FacebookRoundedIcon from "@mui/icons-material/FacebookRounded";
import GoogleIcon from "@mui/icons-material/Google";

export default function LoginPage() {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Stack direction="row">
          <Box flex={1} bgcolor="#fff" height="100vh" color="#000">
            <img
              src="/img/bg-login.png"
              width="100%"
              alt="img"
              className="img-fluid"
            />
          </Box>
          <Box
            flex={1}
            bgcolor="#fff"
            height="100vh"
            color="#000"
            padding={2}
            display="flex"
            alignItems="center"
          >
            <Stack alignItems="center" gap={2} maxWidth={600} flex={1}>
            <h1 className="m-0">-Đăng Nhập</h1>
              <p>Xin chào, vui lòng điền vào thông tin đăng nhập</p>
              <TextField
                id="outlined-basic"
                label="Tên Đăng Nhập"
                variant="outlined"
                sx={{
                  marginTop: 2,
                  width: "100%",
                }}
              />
              <TextField
                id="outlined-basic"
                label="Mật khẩu"
                variant="outlined"
                sx={{
                  width: "100%",
                }}
              />
              <Button
                variant="contained"
                color="primary"
                fullWidth
                sx={{
                  marginTop: 3,
                }}
              >
                ĐĂNG NHẬP
              </Button>
              <Box textAlign="right" width="100%">
                <a href="/quen-mat-khau" className="text-primary">
                  <small>Quên mật khẩu?</small>
                </a>
              </Box>
              <Box textAlign="center">
                <small>Hoặc</small>
              </Box>
              <Stack justifyContent="center" direction="row" gap={3}>
                <IconButton>
                  <FacebookRoundedIcon />
                </IconButton>
                <IconButton>
                  <GoogleIcon />
                </IconButton>
              </Stack>
              <Box>
                Bạn chưa có tài khoản?{" "}
                <a href="/register" className="text-primary">
                  Đăng ký ngay
                </a>
              </Box>
            </Stack>
          </Box>
        </Stack>
      </Box>
    </div>
  );
}
