import { useState } from "react";
import {
  Box,
  Breadcrumbs,
  Button,
  Checkbox,
  FormControlLabel,
  IconButton,
  Link,
  Rating,
  Stack,
  TextareaAutosize,
  TextField,
  Typography,
} from "@mui/material";
import LocalPhoneOutlinedIcon from "@mui/icons-material/LocalPhoneOutlined";
import Head from "next/head";
import RemoveIcon from "@mui/icons-material/Remove";
import AddIcon from "@mui/icons-material/Add";

import Footer from "../components/Footer";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import NavigateNextIcon from "@mui/icons-material/NavigateNext";
import { ProductProps } from "../components/Product";
import Products from "../components/Products";

const Home = () => {
  const [count, setCount] = useState(0);
  const products1: ProductProps[] = [{
    name: "Đèn bàn vintage",
    img: "/img/products/prod2.png",
    price: 200000,
    discount: 20,
  },
  {
    name: "Đèn cổ điển",
    img: "/img/products/pro3.png",
    price: 200000,
    discount: 20,
  },
  {
    name: "Đèn treo thủy tinh",
    img: "/img/products/pro4.png",
    price: 200000,
    discount: 20,
  },
  {
    name: "Đèn đồng thau",
    img: "/img/products/prod5.png",
    price: 200000,
    discount: 20,
  }
  ];

  const handleIncrease = () => setCount((prev) => prev + 1);
  const handleDecrease = () => setCount((prev) => prev - 1);

  const categories = [
    "KHUYẾN MÃI",
    "SẢN PHẨM MỚI",
    "ĐÈN LED BÚP",
    "ĐÈN TUÝP LED",
    "ĐÈN LED PANEL",
    "ĐÈN PHA LED",
  ];
  const breadcrumbs = [
    <Link underline="hover" key="1" color="inherit" href="/">
      Trang Chủ
    </Link>,
    <Link underline="hover" key="2" color="inherit" href="/">
      khuyến mãi
    </Link>,
    <Typography key="3" color="primary">
      Đèn bàn vintage
    </Typography>,
  ];

  const product: ProductProps = {
    name: "Đèn bàn vintage",
    img: "/img/products/prod2.png",
    price: 2400000,
    discount: 0,
  };

  return (
    <div>
      <Head>
        <title>Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Header categories={categories} />
        <Navbar />
        <Box maxWidth={1024} p={2} m="auto" borderTop="1px solid #dddd">
          <Breadcrumbs
            separator={<NavigateNextIcon fontSize="small" />}
            aria-label="breadcrumb"
          >
            {breadcrumbs}
          </Breadcrumbs>
        </Box>
        <Box maxWidth={1024} p={2} m="auto">
          <Stack direction="row">
            <Box flex={1} bgcolor="#fff" color="#000">
              <img
                src={product.img}
                width="100%"
                alt="img"
                className="img-fluid"
              />
            </Box>
            <Box
              flex={1}
              bgcolor="#fff"
              color="#000"
              padding={2}
              display="flex"
            >
              <Stack gap={2} flex={1}>
                <h2 className="m-0">KHUYẾN MẠI</h2>
                <Typography
                  className="text-primary"
                  fontSize={34}
                  fontWeight="bold"
                >
                  {product.name}
                </Typography>
                <Rating name="read-only" value={4} readOnly />
                <span>Công suất:7W</span>
                <span>Điện áp:220V/50Hz</span>
                <span>Nhiệt độ màu:6500k/3000k</span>
                <span>Quang thông:560Im</span>
                <span>Góc phát hiện của Rada:90 độ</span>
                <span>Chiều cao lắp đặt:(2.8-3.5)m</span>
                <span>Đường kính khoét trần:90mm</span>
                <span>Kích thước(ØxC):(110×51)mm</span>
                <Box borderBottom="1px solid #dddd" mt={4} />
                <Typography
                  className="text-primary"
                  fontSize={34}
                  fontWeight="bold"
                >
                  {product.price.toLocaleString()}
                </Typography>
                <Stack direction="row" alignItems="center" gap={1}>
                  <IconButton onClick={handleDecrease}>
                    <RemoveIcon />
                  </IconButton>
                  <span>{count}</span>
                  <IconButton onClick={handleIncrease}>
                    <AddIcon />
                  </IconButton>
                </Stack>
                <Button
                  variant="contained"
                  color="primary"
                  fullWidth
                  sx={{
                    marginTop: 3,
                    textTransform: "capitalize",
                  }}
                >
                  Thêm vào giỏ
                </Button>
                <Box borderBottom="1px solid #dddd" mt={4} />
                <p>Vui long lien he</p>
                <Stack
                  direction="row"
                  alignItems="center"
                  gap={2}
                  className="text-primary"
                >
                  <LocalPhoneOutlinedIcon />
                  <span>0532262666</span>
                </Stack>
              </Stack>
            </Box>
          </Stack>
          <Box borderBottom="1px solid #dddd" mt={4} />
          <Box mb={5}>
            <h1>Mô tả</h1>
            <p>
            Đèn bàn vintage Rạng Đông là giải pháp hiệu quả trong mùa dịch Covid-19. Ngoài khả năng chiếu sáng vượt trội, đèn còn mang đến khả năng diệt sạch virus trong không khí lên tới 99%. Sản phẩm là giải pháp chiếu sáng vô cùng cần thiết nhằm đảm bảo an toàn sức khỏe cho gia đình bạn.
Cấu tạo đèn diệt khuẩn rạng đông
<br/>
– Tích hợp Chip LED UV-C khi bật sẽ tiêu diệt 99.9% vi sinh vật có hại.
<br/>
– Tích hợp công nghệ cảm biến radar, đèn hoạt động thông minh với 2 chế độ tiện ích:
<br/>
+ Tự động sáng như đèn thường khi có người và bật chế độ khử khuẩn khi người rời đi (Chế độ tự động).
<br/>
+ Người dùng cũng có thể tùy ý sử dụng đèn thường hay đèn khử khuẩn bằng công tắc ON/OFF (Chế độ thủ công).
<br/>
– Không chỉ hoạt động như đèn  khử khuẩn, đèn Downlight diệt khuẩn Rạng Đông còn được dùng với chế độ chiếu sáng thông thường bởi:
<br/>
– Thiết kế tinh tế hiện đại.
<br/>
– 2 màu ánh sáng trắng 6500K và vàng 3500K để khách hàng lựa chọn cho các không gian khác nhau chẳng hạn như phòng khách hay phòng ngủ.
<br/>
– Lắp cố định trên trần nhà, không phải cầm di chuyển nhiều nơi.

            </p>
          </Box>
          <Box mb={5}>
            <h1>Đánh giá</h1>
            <p>Chưa có đánh giá nào.</p>
            <fieldset className="p-2">
              <h2>Hãy là người đầu tiên nhận xét “Đèn bàn vintage”</h2>
              <p>Đánh giá của bạn</p>

              <Rating name="read-only" value={4} />
              <Stack direction="row" gap={3}>
                <TextField
                  id="outlined-basic"
                  label="Tên"
                  variant="outlined"
                  sx={{
                    marginTop: 2,
                    width: "100%",
                  }}
                />
                <TextField
                  id="outlined-basic"
                  label="Email"
                  variant="outlined"
                  sx={{
                    marginTop: 2,
                    width: "100%",
                  }}
                />
              </Stack>

              <TextField
                id="outlined-multiline-static"
                label="Nhận xét của bạn"
                multiline
                rows={4}
                fullWidth
                sx={{ marginTop: 4, marginBottom: 3 }}
              />
              <FormControlLabel
                control={<Checkbox defaultChecked />}
                label="Lưu tên của tôi, email, và trang web trong trình duyệt này cho lần bình luận kế tiếp của tôi"
                sx={{
                  width: "100%",
                  marginBottom: 1,
                }}
              />
              <Button variant="contained" color="primary">
                Gửi
              </Button>
            </fieldset>
          </Box>
          <Products title="Các sản phẩm tương tự" products={products1} />
        </Box>
        <Footer />
      </Box>
    </div>
  );
};
export default Home;
