import { useState } from "react";
import {
  Box,
  Breadcrumbs,
  Button,
  Checkbox,
  FormControlLabel,
  IconButton,
  Link,
  Rating,
  Stack,
  TextareaAutosize,
  TextField,
  Typography,
} from "@mui/material";
import LocalPhoneOutlinedIcon from "@mui/icons-material/LocalPhoneOutlined";
import Head from "next/head";
import RemoveIcon from "@mui/icons-material/Remove";
import AddIcon from "@mui/icons-material/Add";

import Footer from "../components/Footer";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import NavigateNextIcon from "@mui/icons-material/NavigateNext";
import { ProductProps } from "../components/Product";
import Products from "../components/Products";

const Home = () => {
  const [count, setCount] = useState(0);
  const products1: ProductProps[] = Array(4).fill(null);

  const handleIncrease = () => setCount((prev) => prev + 1);
  const handleDecrease = () => setCount((prev) => prev - 1);

  const categories = [
    "Khuyen mai",
    "san pham moi",
    "den led",
    "den tuyt",
    "den led panel",
    "den pha led",
  ];
  const breadcrumbs = [
    <Link underline="hover" key="1" color="inherit" href="/">
      Trang Chur
    </Link>,
    <Link underline="hover" key="2" color="inherit" href="/">
      khuyen mai
    </Link>,
    <Typography key="3" color="primary">
      Den ban vintage
    </Typography>,
  ];

  const product: ProductProps = {
    name: "Den ban",
    img: "/img/bg-login.png",
    price: 2400000,
    discount: 0,
  };

  return (
    <div>
      <Head>
        <title>Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Header categories={categories} />
        <Navbar />
        <Box maxWidth={1024} p={2} m="auto" borderTop="1px solid #dddd">
          <Breadcrumbs
            separator={<NavigateNextIcon fontSize="small" />}
            aria-label="breadcrumb"
          >
            {breadcrumbs}
          </Breadcrumbs>
        </Box>
        <Box maxWidth={1024} p={2} m="auto">
          <Stack direction="row">
            <Box flex={1} bgcolor="#fff" color="#000">
              <img
                src={product.img}
                width="100%"
                alt="img"
                className="img-fluid"
              />
            </Box>
            <Box
              flex={1}
              bgcolor="#fff"
              color="#000"
              padding={2}
              display="flex"
            >
              <Stack gap={2} flex={1}>
                <h2 className="m-0">Khuyen mai</h2>
                <Typography
                  className="text-primary"
                  fontSize={34}
                  fontWeight="bold"
                >
                  {product.name}
                </Typography>
                <Rating name="read-only" value={4} readOnly />
                <span>Coong suaat</span>
                <span>Coong suaat</span>
                <span>Coong suaat</span>
                <span>Coong suaat</span>
                <span>Coong suaat</span>
                <span>Coong suaat</span>
                <span>Coong suaat</span>
                <Box borderBottom="1px solid #dddd" mt={4} />
                <Typography
                  className="text-primary"
                  fontSize={34}
                  fontWeight="bold"
                >
                  {product.price.toLocaleString()}
                </Typography>
                <Stack direction="row" alignItems="center" gap={1}>
                  <IconButton onClick={handleDecrease}>
                    <RemoveIcon />
                  </IconButton>
                  <span>{count}</span>
                  <IconButton onClick={handleIncrease}>
                    <AddIcon />
                  </IconButton>
                </Stack>
                <Button
                  variant="contained"
                  color="primary"
                  fullWidth
                  sx={{
                    marginTop: 3,
                    textTransform: "capitalize",
                  }}
                >
                  Theem vafo gio
                </Button>
                <Box borderBottom="1px solid #dddd" mt={4} />
                <p>Vui long lien he</p>
                <Stack
                  direction="row"
                  alignItems="center"
                  gap={2}
                  className="text-primary"
                >
                  <LocalPhoneOutlinedIcon />
                  <span>0999888777</span>
                </Stack>
              </Stack>
            </Box>
          </Stack>
          <Box borderBottom="1px solid #dddd" mt={4} />
          <Box mb={5}>
            <h1>Moo tar</h1>
            <p>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum.
            </p>
          </Box>
          <Box mb={5}>
            <h1>Danh gia</h1>
            <p>Chua co danh gia</p>
            <fieldset className="p-2">
              <h2>Hay la ng d</h2>
              <p>dang gia cua b</p>

              <Rating name="read-only" value={4} />
              <Stack direction="row" gap={3}>
                <TextField
                  id="outlined-basic"
                  label="Tên Đăng Nhập"
                  variant="outlined"
                  sx={{
                    marginTop: 2,
                    width: "100%",
                  }}
                />
                <TextField
                  id="outlined-basic"
                  label="Tên Đăng Nhập"
                  variant="outlined"
                  sx={{
                    marginTop: 2,
                    width: "100%",
                  }}
                />
              </Stack>

              <TextField
                id="outlined-multiline-static"
                label="Multiline"
                multiline
                rows={4}
                fullWidth
                sx={{ marginTop: 4, marginBottom: 3 }}
              />
              <FormControlLabel
                control={<Checkbox defaultChecked />}
                label="Luu ten cua toi"
                sx={{
                  width: "100%",
                  marginBottom: 1,
                }}
              />
              <Button variant="contained" color="primary">
                Guwri
              </Button>
            </fieldset>
          </Box>
          <Products title="Cas sp tuowng tu" products={products1} />
        </Box>
        <Footer />
      </Box>
    </div>
  );
};
export default Home;
